sudo: false
language: python
matrix:
  include:
  - python: '3.6'
    env: LTD_MASON_BUILD=true
install:
- pip install -r requirements.txt
- pip install "ltd-mason>=0.2,<0.3"
script:
- sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
- ltd-mason-travis --html-dir _build/html
env:
  global:
  - LTD_MASON_BUILD=false
  - LTD_MASON_PRODUCT="dmtn-112"
  - secure: rC++fQSBTe+4jNWEiNpF2y0iaYvjgYYc6HqgOK0qFVtNksbTTPjmYSQGmK82BM+9Eimupx3odVXtGrMkLvezQKmW/ri8Q+ts8G7OfldXFGPmTPz4wMPGQXbgd4G/19Ye9wnXNzir/rOflz6z6QDemajODpPDKwCgFE3+McGqHobLZd+/4TG8XmNrcM8/Q94ojCvkBadRn5JdfHu2SR0HnB1EcWJfoQq/VAEsAB1piJzBRcZY2NYYrYcW8s/HZdVeoImVM0revVohVaM+RIDC0yhGYEW7StTX/G29A4LKJKY9ITN4jvbpdXO6OhHstsMSagsmBS9dYKv8na/ZmgoIQNsMS4t0N/3xEGf3wapJPp8FgLtVEzxQ4WyR/UL2fQPlIabJF3E5czGSkphfU3fmI6hDJCZ1OZ9XWRNSShEKX8Vuoe5lIkZYMWZd5V629iM8UR3aL8ryDw2nsVM3LMbYAb45H8wcI+BMeXw3oVpN4mOKmFPzA9UxxYgRtBdcefzA7m0J5BtHHeCFw0iK9ef6jm0g8RFMoWJFRlebo+dnkDOHcI3ssL6ES77NThuKu5+mQvKlLmCsC1y6sT5nE/XiXXuT5dJLeDFfYNsMkn4XJozdCyGF/ERu4OvW8CjPtodo1i7a2kiU1eUuz9Q/Ye1Npnh2Yqyao9nVSpUX4kjzoPc=
  - secure: IbbwznV6FVh2oZEYllIWlhnaudE0VlaVAYrmc3Iqr4lIp+R6DmDL7RkIu5JUzYxdF3t6eUaGaKO64r6qS0oko9Abd8654HYzVfYq62mu6pF056XkwOamwQLr2IvxQlh0GK6ydEZutvhPjFf+Fzvnn7eCmv5Kzxu6vlO9zTxp1U51lvD7PobzPj99QZb3vfGTbW7OanB/0TlJ7ms4PfFN+uBBL2u8uRIlzoCDulwgbLOSFqQokYoBCKgF3XSvSK70ualefXNOjkESqRLq3gSgD0trdv0mIY9zOJpHSv88SVQrI0vEp9CisZjzkCRHHoKZ5QcZxRA9ehbhZNWPP3S380+lH1smRdR2x3j0JhW1q4ja7ZRSu34lqksfLp22wdwCvmh50wdxWNo7SXGu+SJijNKCvqtHj+4rDoK9MUxbVu3BNQPa4BQY1+Fl4P+tcqTuj0J5HdnPOxc7xpLx0v47Vv/bvkdQXdS2tfSA6M10JPH8f+dY4P6dAlEX74v7tkeN7/i+YucUQYhVu60VfqkL++YEY6BWIbe1yRQHRocxqdTHPfyH7o14pBMDR4y/MfvOiSn2ruUfyNcNMRKwITQTWVK/SRsjEORwHefIkFypsLzoD0OrFZ30pTKqGIyyIbrxjWdLn8LlRP83UtFX+4eZwYXZ5yfttQKvx5/BhSGv3rY=
