sudo: false
language: python
matrix:
  include:
  - python: '3.6'
    env: LTD_MASON_BUILD=true
install:
- pip install -r requirements.txt
- pip install "ltd-mason>=0.2,<0.3"
script:
- sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
- ltd-mason-travis --html-dir _build/html
env:
  global:
  - LTD_MASON_BUILD=false
  - LTD_MASON_PRODUCT="dmtn-112"
  - secure: "UG8HWQiRVpybWThHGuzqPclBnsiHseCWg9jSN38OPm33DLJuQRm/Tid+NfiNMvVbfHJfIYoecSzckAPVMRNcrO7qA1B4Y3cUUzToBOlP4YpoFCANcPd0w4d55jR3nZ2aBKNf3wPgYc+JMFtKdcEeG6BoMMa96RWMdUHv+YlJ5Iu3vuExO5i3dZM60IhreB6vEs0XV7wx2H5jrCdoXN7k/Rn0Gjv/ZeB6fumV3w/rNGzt7v7zJ9Tz2bNpZxWdC6sqc4qMxMSA7ABVao/94LQKZwKpDqKd44K1UgjhRJCxKvYXEAG9C7/z0f14GvhaOR6wPq3kZgExBmT6/76pgMM6E9hp87Yjf4+ROqwMd02l3wI9Sv4lGV/J3GOUvpZf0UI91/Q3jIVd+927henV6Ib41E2mpH4ha0YCOkQZMcG09khz+DulgXwChxG4WlbSmQwDFH40PfdJ5+ZJ8H+sXzLSFpuqrIjW7JzzaEl/1OyU38wepbZk3QXxvepQqwFJ4MJ0/5M7DYBc/F0TClMQWzMaA5A6+g0lpajV9aPy22fBM4Z17P9AYE+JI24lF/mqfVBtO4hj033rcmH2KOPkK9DmVqaIgMsRyXibOTCI+4BrGNY4S5uKp+iuwW1+n8s35pdhDNIeBFWqQPk1TwRTNvbH2/yVz9GVwpyDNCYwPd3dj94="
  - secure: "jecLKZUUYdGvc3sSSg0yUDWRGAt16VjX+QYA0X9UzK+tRCWaYCPsXSo0HhwQy16KhTySdQQ4f4XilHO4HVXtNJS4d5vBPlZrQCYioAPAxGyyL6ZXkqwgYezVQA5W3J61QqQDepDhvcEpr3YPMx1JimiGWhYu/H1wNAc/5ykv7lllJaaf8V+NNn+vgk0GPruzw+C1N2SpWOsBgEgvlceN4ck755p95auba7ptRvPFveqv/yaSbcc7jabRpXxKkES/z8ZrXMNsfPY2gPNIVkn/sy1TE7RnBMTI2OADe1z8ftjlb/Ou5MCklycwoW8OY7zEq/4TAH8p2zt+I8kdk9XZXLK1TZa1XuFFx++woOjt2ikzYZwRKip5vzW0rZ9jPW5+EAYLoh1rdpusdNtF+FnL/miHtjmUd+K6HxtSlr4wy4sLju7JiCUIup4eJ7Fpg/eJKNXtl0lv6Bp8FwUvwOgg39zZ2Xt8s8tfC6xIYpPlFBqT8imilCrvp0EgSSi+kyOMTlQOm8PZ1kuWjtl4ZNToO2cBMbJPhMdIVWIHmre3v6vE3VIK3JK2J6X208tTiq2NVn+5Qa+BkrTvR/4Ujb8F9V99bmSjm+9KkEGgDMSmOzeZAeUPD7LLDWtPg2NFbdHR7g/ZGkCvwf6FK873XJ+QXZTQmSzFEPn6y65sbctgFEw="
